language: ruby

install:

  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --trace

env:
  global:
    secure: "AOIpQNsD6xap5uXvymJnyR2kIPaGzrdMwmL483ggetABxrwMbBOUf+8zDQWDwQQkpW/KwzPKT6Ncbhb/RvQzZmoXZKz6bR2Mo0ZAh0U8q++VJ+sTXxm7P56LG/awNF5UP0er1dw1b3iHs3khWenRIfjoVgPUXG3SWflU7ru5Mseb77Ua7OTjhPP9NhXkGzYZ006LF/JqtGkArYofCLGHZFjAtf4RCffTKSwFvifQHS7jMt/w7MkTHXfHSz0pNtMu2/zkLOGZW3SI+h60/kSpr/mZxe4Ho6+L5qWPAB046DWu/5gBQxpD1Xw99jmpjTVjAdLYKBVNoZyNo3EnDPf7AMDvCl5AwS+vGr6jfBJIgT49On47ud4wxMVijTg9cNeaYp4Z/tMv8azjYnxYrOHEYRnQgkcRpPAS+4GYWdMFjYIVVUqPTbWh/sN25x1fjlKSmhLQ6cxwiVsjXKvdL7vmq53FnC5PKFquiyWEBVBqoEZFS5rfwfZNjAkzR9p/RjL72k+U80kMBjBk7xkGbhaY6usutuqaSN27cfIwHa+r1/Fd+MVkXXSQ0yaTTXFke0b/Id4IvKHEU2mUjAY47WblpS+0HBNYSk6TGOgnq9P0JBEIN7AWAf7p/rlJLBtLB5u78b9tHhK3ZcwoX7qGFb/16e/c7QGFhAREXTKvvUpeJD8="
