title: "Blog | Mayant Mukul"
email: "mayantmukul@hotmail.com"
description: A simple blog for me to record my activities.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]


# Jekyll configuration
####################################

timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  math_engine: mathjax
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site Owner configuration
####################################

owner:
  name: "Mayant Mukul"
  avatar: jungfrau.jpg
  job: "Mathematics Undergraduate"
  bio: ""
  email: "mayantmukul@hotmail.com"
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mayant15
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: mayant-mukul-222086172
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
