title: Blog
description: My thoughts on math and programming
meta_description: "Mayant Mukul's blog on math and programming"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://mayant15.github.io"
plugins: [
  jekyll-paginate
]

# Details for the RSS feed generator
url: ""
author: "Mayant Mukul"
