baseURL = 'https://mayantmukul.com/'
languageCode = 'en-in'
title = 'Mayant Mukul'
theme = 'archie'

# Theme params

[params]
mode = 'light'
useCDN = false
katex = true
# subtitle = 'Tinkering with stuff'

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/mayant15'

[[params.social]]
name = 'LinkedIn'
icon = 'linkedin'
url = 'https://www.linkedin.com/in/mayant-mukul-222086172/'

# [[menu.main]]
# name = 'Home'
# url = '/'
# weight = 1

[[menu.main]]
name = 'Posts'
url = '/posts'
weight = 1

[[menu.main]]
name = 'About'
url = '/about'
weight = 2

