baseURL = 'https://mayantm.com/'
languageCode = 'en-ca'
title = 'Mayant Mukul'
theme = 'archie'

# Theme params

[params]
mode = 'light'
subtitle = 'PhD student at [UBC Software Practices Lab](https://spl.cs.ubc.ca/index.html) supervised by [Caroline Lemieux](https://www.carolemieux.com/). Currently working on fuzz testing.'
blurb ="""I am broadly interested in practical solutions to make software simpler, safer, and
faster. Specifically, I am working on automated testing and program analysis. My current work
focuses on expanding the applicability of fuzz testing to JavaScript libraries in a way that
addresses the many quirks of dynamic languages."""
customcss = ["css/custom.css"]

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/mayant15'

[[params.social]]
name = 'LinkedIn'
icon = 'linkedin'
url = 'https://www.linkedin.com/in/mayant-mukul-222086172/'

[[params.social]]
name = 'Email'
icon = 'mail'
url = 'mailto:mayant.mukul@ubc.ca'

# Goldmark passthrough lets math expressions through, then a render hook
# renders them later.
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\\[', '\\]'], ['$$', '$$']]
inline = [['\\(', '\\)'], ['$', '$']]
